# Jwt 토큰에 들어가는 secret 값
spring:


# jpa
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true

  # database 연결관련, 개발환경 (mysql)
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/halal?createDatabaseIfNotExist=true
    username: root
    password: ?Qweasd7410

  # 배포환경은 (maria DB)
