# Jwt 토큰에 들어가는 secret 값
spring:
  jwt:
    secret: asd


# jpa
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true

  # database 연결관련
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://svc.sel5.cloudtype.app:31347/halal?createDatabaseIfNotExist=true
    username: root
    password: ?Qweasd7410
